first part was implemented
Mandybur800/manufacturing-DAO3 pull request #1
Opened 2021-01-11 13:17 UTC by Mandybur800

2021-01-11 13:46 UTC, Max-Pochepets approved these changes

2021-01-12 07:30 UTC, Sofasmile requested changes
good job)

2021-01-12 07:30 UTC, Sofasmile commented on pom.xml
>  </project>
let's add empty line at the end of the file

2021-01-12 07:30 UTC, Sofasmile commented on src/main/java/com/manufacturing/dao/impl/ManufacturerDaoImpl.java
> +        manufacturer.setName(manufacturerUpdate.getName());
this code isn't flexible. We should change the logic of this method if the manufacturer object is changed

let's use the method `set` from the list for replacing an object

2021-01-12 07:30 UTC, Sofasmile commented on src/main/java/com/manufacturing/dao/impl/ManufacturerDaoImpl.java
> +                return Storage.manufacturers.remove(manufacturer);
we can use method `removeIf()`

2021-01-12 07:30 UTC, Sofasmile commented on src/main/java/com/manufacturing/service/impl/ManufacturerServiceImpl.java
> +    ManufacturerDao manufacturerDao;
let's add access modifier)

2021-01-12 07:30 UTC, Sofasmile commented on src/main/java/com/manufacturing/dao/ManufacturerDao.java
> +    List<Manufacturer> getAllManufacturers();
```suggestion
    List<Manufacturer> getAll();
```

2021-01-12 10:46 UTC, Sofasmile approved these changes

2021-01-12 10:46 UTC, merged