part two was implemented
Mandybur800/manufacturing-DAO3 pull request #2
Opened 2021-01-12 12:03 UTC by Mandybur800

2021-01-12 20:34 UTC, Vedroid approved these changes

2021-01-13 08:23 UTC, RomanDubovskyi requested changes

2021-01-13 08:23 UTC, RomanDubovskyi commented on src/main/java/com/manufacturing/service/impl/CarServiceImpl.java
> +        return carDao.get(id).orElseThrow();
```suggestion
        return carDao.get(id).get();
```
id you don't throw any particular exception with a message, its' shorter to call get

2021-01-13 08:23 UTC, RomanDubovskyi commented on src/main/java/com/manufacturing/service/impl/CarServiceImpl.java
> +                .collect(Collectors.toList());
let's move this to dao layer. When you connect your db to the project you will write SQL statements with parameters and receive already sorted data from db

2021-01-13 08:23 UTC, RomanDubovskyi commented on src/main/java/com/manufacturing/service/impl/DriverServiceImpl.java
> +        return driverDao.get(id).orElseThrow();
same here

2021-01-13 08:23 UTC, RomanDubovskyi commented on src/main/java/com/manufacturing/service/impl/CarServiceImpl.java
> +        if (!driverDao.getAll().contains(driver)) {
let's remove this check, when you connect db, it will handle this case and throw exception if there is no driver in db.

2021-01-13 09:28 UTC, RomanDubovskyi approved these changes
good job

2021-01-13 09:29 UTC, merged