part 6 was implemented
Mandybur800/manufacturing-DAO3 pull request #6
Opened 2021-01-20 13:01 UTC by Mandybur800

2021-01-20 13:15 UTC, Vedroid requested changes

2021-01-20 13:15 UTC, Vedroid commented on src/main/java/com/manufacturing/controllers/car/AddDriverToCarController.java
> +        Driver driver = driverService.get(driverId);
What if the specified id is not in the database?

2021-01-20 13:15 UTC, Vedroid commented on src/main/java/com/manufacturing/controllers/car/CreateCarController.java
> +        Car car = new Car(model, manufacturerService.get(manufacturerId));
What if the specified id is not in the database

2021-01-20 13:15 UTC, Vedroid commented on src/main/webapp/web.xml
> +        <url-pattern>/car/addDriver</url-pattern>
Bad URLs naming
[checklist](https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/08_servlets_practice_checklist.html)

2021-01-20 13:44 UTC, Vedroid approved these changes

2021-01-21 09:42 UTC, dmytro-hryhoruk approved these changes
Good job! Add tabulations to tag in jsp files where needed

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/java/com/manufacturing/controllers/car/AddDriverToCarController.java
> +            req.getRequestDispatcher("/WEB-INF/views/incorrect.jsp").forward(req, resp);
you may add an exception as an attribute and show it in the incorrect page

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/java/com/manufacturing/controllers/car/CreateCarController.java
> +            String manufacturer = req.getParameter("manufacturer");
```suggestion
            Long manufacturerId = Long.parseLong(req.getParameter("manufacturer_id"));
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/java/com/manufacturing/controllers/car/CreateCarController.java
> +            Long manufacturerId = Long.parseLong(manufacturer);
```suggestion
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/java/com/manufacturing/controllers/car/CreateCarController.java
> +            req.getRequestDispatcher("/WEB-INF/views/incorrect.jsp").forward(req, resp);
same

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/WEB-INF/views/driver/create.jsp
> +    <button type="submit">Create</button>
```suggestion
<form method="post" action="${pageContext.request.contextPath}/driver/create">
    Please, enter name of driver
    <input type="text" name="name" required>
    Please, enter driving license
    <input type="number" name="license" required>
    <button type="submit">Create</button>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/WEB-INF/views/driver/create.jsp
> +</html>
add tabulation to your jsp files

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/WEB-INF/views/manufacturer/create.jsp
> +    Please, enter country of manufacturer<input type="text" name="country" required>
```suggestion
    Please, enter name of manufacturer
    <input type="text" name="name" required>
    Please, enter country of manufacturer
    <input type="text" name="country" required>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/manufacturer/</url-pattern>
```suggestion
        <url-pattern>/manufacturers/</url-pattern>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/driver/</url-pattern>
```suggestion
        <url-pattern>/drivers/</url-pattern>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/car/</url-pattern>
```suggestion
        <url-pattern>/cars/</url-pattern>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/manufacturer/delete</url-pattern>
```suggestion
        <url-pattern>/manufacturers/delete</url-pattern>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/driver/delete</url-pattern>
```suggestion
        <url-pattern>/drivers/delete</url-pattern>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/car/delete</url-pattern>
```suggestion
        <url-pattern>/cars/delete</url-pattern>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/manufacturer/create</url-pattern>
```suggestion
        <url-pattern>/manufacturers/create</url-pattern>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/driver/create</url-pattern>
```suggestion
        <url-pattern>/drivers/create</url-pattern>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/car/create</url-pattern>
```suggestion
        <url-pattern>/cars/create</url-pattern>
```

2021-01-21 09:42 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/car/drivers/add</url-pattern>
```suggestion
        <url-pattern>/cars/drivers/add</url-pattern>
```

2021-01-21 10:05 UTC, merged