part 7 was implemented
Mandybur800/manufacturing-DAO3 pull request #7
Opened 2021-01-21 13:53 UTC by Mandybur800

2021-01-22 09:27 UTC, Max-Pochepets approved these changes
👍

2021-01-22 09:27 UTC, Max-Pochepets commented on src/main/java/com/manufacturing/controllers/LoginController.java
> +        String password = req.getParameter("pwd");
```suggestion
        String password = req.getParameter("password");
```
:)

2021-01-22 09:27 UTC, Max-Pochepets commented on src/main/java/com/manufacturing/controllers/driver/CreateDriverController.java
> +        }
we don't need to repeat the password in the scope of this task

2021-01-22 09:27 UTC, Max-Pochepets commented on src/main/java/com/manufacturing/security/AuthenticationServiceImpl.java
> +        Driver byLogin = driverService.findByLogin(login)
```suggestion
        Driver driverByLogin = driverService.findByLogin(login)
```

2021-01-22 10:54 UTC, Ketch92 approved these changes

2021-01-22 10:54 UTC, Ketch92 commented on src/main/java/com/manufacturing/web/filters/AuthenticationFilter.java
> +        }
you can make it work with a single if construction

2021-01-25 16:40 UTC, RomanDubovskyi requested changes

2021-01-25 16:40 UTC, RomanDubovskyi commented on src/main/java/com/manufacturing/security/AuthenticationServiceImpl.java
> +        throw new AuthenticationException("Incorrect login or password");
```suggestion
        Optional<Driver> driverByLogin = driverService.findByLogin(login);
        if (driverByLoging.isPresent() && driverByLogin.get().getPassword().equals(password)) {
            return driverByLogin;
        }
        throw new AuthenticationException("Incorrect login or password");
```

2021-01-25 16:40 UTC, RomanDubovskyi commented on src/main/java/com/manufacturing/web/filters/AuthenticationFilter.java
> +            return;
it's optional but ideally, we can replace it with Set, so this construction will be more readable when the number of URLs grows.

2021-01-25 16:40 UTC, RomanDubovskyi commented on src/main/java/com/manufacturing/web/filters/AuthenticationFilter.java
> +    private final DriverService driverService = (DriverService)
do we use it anywhere?

2021-01-26 07:45 UTC, RomanDubovskyi approved these changes
Good job 👍

2021-01-26 07:45 UTC, RomanDubovskyi commented on src/main/java/com/manufacturing/web/filters/AuthenticationFilter.java
> +    private final Set<String> urls = new HashSet<>();
```suggestion
    private final Set<String> allowedUrls = new HashSet<>();
```
URLs name is a bit ambigours

2021-01-26 08:00 UTC, merged